export const availablefacets = [
  "CASE_TYPE",
  "GOOD_CAUSE_STATUS",
  "REFERRAL_STATUS",
  "STATUS",
  "CLOSURE_REASON",
  "COOPERATION",
  "MA_COVERAGE_GROUP",
  "OTHER_INAPPR_REASON_DESC",
  "OTHER_REJECT_REASON_DESC",
  "PROGRAM_CASE_NUMB",
  "PROGRAM_OFFICE",
  "REFERRAL_REASON",
];
